name: Frontend_deployment

on:
    push:
        branches: [ main ]
        paths:
            - 'backend/'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
            az storage blob upload-batch --account-name websitekingu --auth-mode key -d '$web' -s frontend/
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "websitejojo" --name "staticjojoweb" --resource-group "static_website_jojo"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()